################################################################################
# File: pipeline/azure-pipelines.yml
# Purpose: Azure DevOps pipeline for CIS hardening automation (4-tier)
# Author: DevOps Automation Team
# Last Updated: October 22, 2025
################################################################################

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - docs/*

pr:
  branches:
    include:
      - main
      - develop

variables:
  - template: variables/common-vars.yml

stages:
  ################################################################################
  # Stage 1: Pre-Check
  ################################################################################
  - stage: PreCheck
    displayName: 'Pre-Check Stage'
    jobs:
      - template: templates/precheck-stage.yml

  ################################################################################
  # Stage 2: Backup
  ################################################################################
  - stage: Backup
    displayName: 'Backup Stage'
    dependsOn: PreCheck
    condition: succeeded()
    jobs:
      - template: templates/backup-stage.yml

  ################################################################################
  # Stage 3: Hardening (Dev)
  ################################################################################
  - stage: HardeningDev
    displayName: 'Hardening - DEV'
    dependsOn: Backup
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - template: templates/hardening-stage.yml
        parameters:
          environment: 'dev'
          inventory: 'inventory/dev/hosts.yml'
          variablesFile: 'variables/dev-vars.yml'

  ################################################################################
  # Stage 4: Validation (Dev)
  ################################################################################
  - stage: ValidationDev
    displayName: 'Validation - DEV'
    dependsOn: HardeningDev
    condition: succeeded()
    jobs:
      - template: templates/validation-stage.yml
        parameters:
          environment: 'dev'
          inventory: 'inventory/dev/hosts.yml'

  ################################################################################
  # Stage 5: Hardening (Test)
  ################################################################################
  - stage: HardeningTest
    displayName: 'Hardening - TEST'
    dependsOn: ValidationDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - template: templates/hardening-stage.yml
        parameters:
          environment: 'test'
          inventory: 'inventory/test/hosts.yml'
          variablesFile: 'variables/test-vars.yml'

  ################################################################################
  # Stage 6: Validation (Test)
  ################################################################################
  - stage: ValidationTest
    displayName: 'Validation - TEST'
    dependsOn: HardeningTest
    condition: succeeded()
    jobs:
      - template: templates/validation-stage.yml
        parameters:
          environment: 'test'
          inventory: 'inventory/test/hosts.yml'

  ################################################################################
  # Stage 7: Hardening (QA)
  ################################################################################
  - stage: HardeningQA
    displayName: 'Hardening - QA'
    dependsOn: ValidationTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: templates/hardening-stage.yml
        parameters:
          environment: 'qa'
          inventory: 'inventory/qa/hosts.yml'
          variablesFile: 'variables/qa-vars.yml'
          requireApproval: true

  ################################################################################
  # Stage 8: Validation (QA)
  ################################################################################
  - stage: ValidationQA
    displayName: 'Validation - QA'
    dependsOn: HardeningQA
    condition: succeeded()
    jobs:
      - template: templates/validation-stage.yml
        parameters:
          environment: 'qa'
          inventory: 'inventory/qa/hosts.yml'

  ################################################################################
  # Stage 9: Hardening (Production)
  ################################################################################
  - stage: HardeningProduction
    displayName: 'Hardening - PRODUCTION'
    dependsOn: ValidationQA
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: templates/hardening-stage.yml
        parameters:
          environment: 'production'
          inventory: 'inventory/production/hosts.yml'
          variablesFile: 'variables/prod-vars.yml'
          requireApproval: true
          batchExecution: true

  ################################################################################
  # Stage 10: Validation (Production)
  ################################################################################
  - stage: ValidationProduction
    displayName: 'Validation - PRODUCTION'
    dependsOn: HardeningProduction
    condition: succeeded()
    jobs:
      - template: templates/validation-stage.yml
        parameters:
          environment: 'production'
          inventory: 'inventory/production/hosts.yml'
          generateComplianceReport: true

  ################################################################################
  # Stage 11: Rollback (Manual Trigger Only)
  ################################################################################
  - stage: Rollback
    displayName: 'Emergency Rollback'
    dependsOn: []
    condition: false  # Manual trigger only
    jobs:
      - template: templates/rollback-stage.yml

################################################################################
# END OF FILE: pipeline/azure-pipelines.yml
################################################################################