################################################################################
# File: roles/rhel_hardening/tasks/logging.yml
# Purpose: CIS Section 4 - Logging and auditing configuration
# Author: DevOps Automation Team
# Last Updated: October 22, 2025
################################################################################

---
# CIS Section 4 - Logging and Auditing

- name: "CIS 4.1.1.x | Configure auditd"
  block:
    - name: "CIS 4.1.1.1 | Ensure auditd is installed"
      package:
        name:
          - audit
          - audit-libs
        state: present

    - name: "CIS 4.1.1.2 | Ensure auditd service is enabled"
      systemd:
        name: auditd
        enabled: yes
        state: started

    - name: "CIS 4.1.1.3 | Ensure auditing for processes prior to auditd is enabled"
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="audit=1"'
        state: present
      notify: update grub

    - name: "CIS 4.1.1.4 | Ensure audit_backlog_limit is sufficient"
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="audit=1 audit_backlog_limit=8192"'
        state: present
      notify: update grub
  when: auditd_enabled | bool
  tags:
    - cis_4.1.1
    - logging
    - auditd

- name: "CIS 4.1.2.x | Configure auditd data retention"
  block:
    - name: "CIS 4.1.2.1 | Configure audit log storage size"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file\s*='
        line: "max_log_file = {{ auditd_max_log_file }}"
        state: present

    - name: "CIS 4.1.2.2 | Configure audit log full action"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file_action\s*='
        line: "max_log_file_action = {{ auditd_max_log_file_action }}"
        state: present

    - name: "CIS 4.1.2.3 | Configure audit log space remaining"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^space_left\s*='
        line: "space_left = {{ auditd_space_left }}"
        state: present

    - name: "CIS 4.1.2.4 | Configure space_left_action"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^space_left_action\s*='
        line: "space_left_action = {{ auditd_space_left_action }}"
        state: present

    - name: "CIS 4.1.2.5 | Configure action_mail_acct"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^action_mail_acct\s*='
        line: "action_mail_acct = {{ auditd_action_mail_acct }}"
        state: present

    - name: "CIS 4.1.2.6 | Configure admin_space_left"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^admin_space_left\s*='
        line: "admin_space_left = {{ auditd_admin_space_left }}"
        state: present

    - name: "CIS 4.1.2.7 | Configure admin_space_left_action"
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^admin_space_left_action\s*='
        line: "admin_space_left_action = {{ auditd_admin_space_left_action }}"
        state: present
  when: auditd_enabled | bool
  notify: restart auditd
  tags:
    - cis_4.1.2
    - logging
    - auditd

- name: "CIS 4.1.3.x | Configure audit rules"
  block:
    - name: "CIS 4.1.3 | Deploy comprehensive audit rules"
      template:
        src: audit.rules.j2
        dest: "{{ auditd_rules_file }}"
        owner: root
        group: root
        mode: '0640'
      notify: restart auditd

    - name: "CIS 4.1.3 | Load audit rules"
      command: augenrules --load
      changed_when: false
  when: auditd_enabled | bool
  tags:
    - cis_4.1.3
    - logging
    - auditd

- name: "CIS 4.2.1.x | Configure rsyslog"
  block:
    - name: "CIS 4.2.1.1 | Ensure rsyslog is installed"
      package:
        name: rsyslog
        state: present

    - name: "CIS 4.2.1.2 | Ensure rsyslog service is enabled"
      systemd:
        name: rsyslog
        enabled: yes
        state: started

    - name: "CIS 4.2.1.3 | Configure rsyslog to send logs to remote host"
      lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @@{{ rsyslog_remote_host }}:514"
        state: present
      when:
        - rsyslog_remote_host is defined
        - rsyslog_remote_host | length > 0
      notify: restart rsyslog
  when: configure_rsyslog | bool
  tags:
    - cis_4.2.1
    - logging
    - rsyslog

- name: "CIS 4.2.2.x | Configure journald"
  block:
    - name: "CIS 4.2.2.1 | Ensure journald is configured to compress large files"
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?Compress='
        line: 'Compress=yes'
        state: present
      when: journald_compress | bool
      notify: restart journald

    - name: "CIS 4.2.2.2 | Ensure journald is configured to write logs to persistent disk"
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?Storage='
        line: 'Storage=persistent'
        state: present
      when: journald_persistent | bool
      notify: restart journald
  when: configure_journald | bool
  tags:
    - cis_4.2.2
    - logging
    - journald

- name: "CIS 4.2.3 | Ensure permissions on all logfiles are configured"
  shell: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  changed_when: false
  tags:
    - cis_4.2.3
    - logging

################################################################################
# END OF FILE: roles/rhel_hardening/tasks/logging.yml
################################################################################