################################################################################
# File: inventory/dev/group_vars/webservers.yml
# Purpose: Web server specific variables for DEV environment
# Environment: DEV
# Author: DevOps Automation Team
# Last Updated: October 22, 2025
################################################################################

---
# NGINX Web Server Configuration (Development)

# NGINX installation
nginx_version: "1.20"
nginx_repo: "https://nginx.org/packages/rhel/8/x86_64/"
nginx_install_method: "package"  # package or source

# NGINX user and group
nginx_user: "nginx"
nginx_group: "nginx"

# NGINX directories
nginx_config_dir: "/etc/nginx"
nginx_log_dir: "/var/log/nginx"
nginx_cache_dir: "/var/cache/nginx"
nginx_lib_dir: "/var/lib/nginx"
nginx_run_dir: "/var/run"

# NGINX service
nginx_service_name: "nginx"
nginx_service_enabled: true
nginx_service_state: "started"

# NGINX worker configuration
nginx_worker_processes: "auto"
nginx_worker_connections: 1024
nginx_multi_accept: "on"

# NGINX performance
nginx_keepalive_timeout: 65
nginx_keepalive_requests: 100
nginx_client_max_body_size: "10m"
nginx_client_body_timeout: 60
nginx_client_header_timeout: 60
nginx_send_timeout: 60

# NGINX logging
nginx_access_log_enabled: true
nginx_access_log_format: "combined"
nginx_error_log_level: "warn"  # debug in dev if needed

# NGINX security headers
nginx_security_headers:
  X-Frame-Options: "SAMEORIGIN"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Content-Security-Policy: "default-src 'self'"

# Hide NGINX version
nginx_hide_version: true
nginx_server_tokens: "off"

# SSL/TLS configuration
ssl_enabled: true
ssl_protocols: "TLSv1.2 TLSv1.3"
ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
ssl_prefer_server_ciphers: "on"
ssl_session_cache: "shared:SSL:10m"
ssl_session_timeout: "10m"
ssl_stapling: true
ssl_stapling_verify: false  # Set to true in prod with proper OCSP

# SSL certificate paths
ssl_certificate_path: "/etc/nginx/ssl/server.crt"
ssl_certificate_key_path: "/etc/nginx/ssl/server.key"
ssl_dhparam_path: "/etc/nginx/ssl/dhparam.pem"
ssl_dhparam_bits: 2048

# Virtual host configuration
nginx_vhosts:
  - server_name: "dev-app.company.local"
    listen_port: 80
    listen_ssl_port: 443
    root: "/var/www/html"
    index: "index.html index.htm"
    access_log: "{{ nginx_log_dir }}/dev-app-access.log"
    error_log: "{{ nginx_log_dir }}/dev-app-error.log"
    ssl_enabled: true

# Firewall rules for web servers
firewall_allowed_ports:
  - 80/tcp    # HTTP
  - 443/tcp   # HTTPS

firewall_allowed_sources:
  - 10.100.0.0/16  # Internal dev network
  - 172.16.0.0/12  # Corporate network

# Application-specific
app_name: "dev-application"
app_version: "1.0.0-dev"
app_deploy_user: "nginx"

# Health check endpoint
health_check_enabled: true
health_check_path: "/health"
health_check_interval: 30

# Rate limiting (disabled in dev)
rate_limiting_enabled: false
rate_limit_requests: 100
rate_limit_burst: 200

# ModSecurity WAF (disabled in dev for testing)
modsecurity_enabled: false

# Monitoring
nginx_status_enabled: true
nginx_status_port: 8080
nginx_status_path: "/nginx_status"

################################################################################
# END OF FILE: inventory/dev/group_vars/webservers.yml
################################################################################