################################################################################
# File: roles/ssl_tls/defaults/main.yml
# Purpose: Default variables for SSL/TLS role
# Author: DevOps Automation Team
# Last Updated: October 22, 2025
################################################################################

---
# SSL/TLS behavior
ssl_enabled: true
ssl_generate_self_signed: false  # Set true for dev/test environments
ssl_force_regenerate: false

# Certificate paths
ssl_certificate_path: "/etc/nginx/ssl/server.crt"
ssl_certificate_key_path: "/etc/nginx/ssl/server.key"
ssl_certificate_chain_path: "/etc/nginx/ssl/ca-bundle.crt"
ssl_dhparam_path: "/etc/nginx/ssl/dhparam.pem"
ssl_trusted_certificate: "/etc/nginx/ssl/ca-bundle.crt"

# Certificate directory
ssl_certificate_dir: "/etc/nginx/ssl"

# Self-signed certificate settings (dev/test only)
ssl_self_signed_country: "US"
ssl_self_signed_state: "State"
ssl_self_signed_locality: "City"
ssl_self_signed_organization: "Company"
ssl_self_signed_organizational_unit: "IT"
ssl_self_signed_common_name: "{{ ansible_fqdn }}"
ssl_self_signed_email: "admin@{{ ansible_domain | default('example.com') }}"
ssl_self_signed_days: 365

# TLS protocols (CIS compliant - TLS 1.2 and 1.3 only)
ssl_protocols: "TLSv1.2 TLSv1.3"

# Cipher suites (Mozilla Modern configuration)
ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"

# Prefer server ciphers
ssl_prefer_server_ciphers: "off"  # TLS 1.3 ignores this

# Session cache
ssl_session_cache: "shared:SSL:10m"
ssl_session_timeout: "10m"
ssl_session_tickets: "off"  # Disabled for better forward secrecy

# DH parameters
ssl_dhparam_bits: 2048  # Use 4096 for production
ssl_dhparam_generate: true

# OCSP stapling
ssl_stapling: true
ssl_stapling_verify: true
ssl_stapling_timeout: "5s"

# HSTS (HTTP Strict Transport Security)
ssl_hsts_enabled: true
ssl_hsts_max_age: 31536000  # 1 year
ssl_hsts_include_subdomains: true
ssl_hsts_preload: false  # Set true only if registered with HSTS preload list

# SSL buffer size
ssl_buffer_size: "16k"

# Early data (0-RTT) - Disabled by default for security
ssl_early_data: false

# Certificate verification depth
ssl_verify_depth: 2

# SSL certificate validation
ssl_validate_certificate: true
ssl_certificate_days_warning: 30  # Warn if cert expires within 30 days

################################################################################
# END OF FILE: roles/ssl_tls/defaults/main.yml
################################################################################